### ISSUE TITLE
Issues ELB Role

### ISSUE THREAD

**Issue by bgrrtt** [arbabnazar/ansible-aws-roles#1]
```
TASK [elb : Ensure load balancer exists] ***************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 1342, in <module>
    main()
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 1326, in main
    elb_man.ensure_ok()
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 410, in _do_op
    return op(*args, **kwargs)
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 493, in ensure_ok
    self.select_stickiness_policy()
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 1042, in select_stickiness_policy
    self._set_stickiness_policy(elb_info, listeners_dict, policy, **policy_attrs)
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 1005, in _set_stickiness_policy
    self._create_policy(policy_attrs['param_value'], policy_attrs['method'], policy[0])
  File "/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py", line 982, in _create_policy
    getattr(self.elb_conn, policy_meth )(policy_param, self.elb.name, policy)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/elb/__init__.py", line 637, in create_lb_cookie_stickiness_policy
    return self.get_status('CreateLBCookieStickinessPolicy', params)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Policy name cannot contain characters that are not letters, or digits or the dash.</Message>
  </Error>
  <RequestId>XXXXXXXXXXXXXX</RequestId>
</ErrorResponse>


fatal: [vagrant]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_elb_lb"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 1342, in <module>\n    main()\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 1326, in main\n    elb_man.ensure_ok()\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 410, in _do_op\n    return op(*args, **kwargs)\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 493, in ensure_ok\n    self.select_stickiness_policy()\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 1042, in select_stickiness_policy\n    self._set_stickiness_policy(elb_info, listeners_dict, policy, **policy_attrs)\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 1005, in _set_stickiness_policy\n    self._create_policy(policy_attrs['param_value'], policy_attrs['method'], policy[0])\n  File \"/tmp/vagrant/ansible_6hqWOb/ansible_module_ec2_elb_lb.py\", line 982, in _create_policy\n    getattr(self.elb_conn, policy_meth )(policy_param, self.elb.name, policy)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/elb/__init__.py\", line 637, in create_lb_cookie_stickiness_policy\n    return self.get_status('CreateLBCookieStickinessPolicy', params)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1227, in get_status\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.BotoServerError: BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Policy name cannot contain characters that are not letters, or digits or the dash.</Message>\n  </Error>\n  <RequestId>XXXXXXXXXXXX</RequestId>\n</ErrorResponse>\n\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by arbabnazar** [comment]
@bgrrtt I think you are using underscore(_) in the ELB name, which is not allowed
